lr : 0.002
epochs : 200
lambda : 10
classes : 10
samples_per_class : 1
class_names : ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
supervised_batch_size : 1
unsupervised_batch_size : 160
tsa_schedule : 'exponential'
